# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 875)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("p27.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 851, 861))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.page = QtWidgets.QWidget(self.gridLayoutWidget)
        self.page.setObjectName("page")
        self.graphicsView = GraphicsView(self.page)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 801, 831))
        self.graphicsView.setInteractive(True)
        self.graphicsView.setObjectName("graphicsView")
        self.label_neuron1 = QtWidgets.QLabel(self.page)
        self.label_neuron1.setGeometry(QtCore.QRect(370, 180, 62, 20))
        self.label_neuron1.setObjectName("label_neuron1")
        self.label_neuron2 = QtWidgets.QLabel(self.page)
        self.label_neuron2.setGeometry(QtCore.QRect(380, 300, 62, 20))
        self.label_neuron2.setObjectName("label_neuron2")
        self.gridLayout.addWidget(self.page, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(910, 30, 259, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_pre = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_pre.setChecked(True)
        self.radioButton_pre.setObjectName("radioButton_pre")
        self.horizontalLayout.addWidget(self.radioButton_pre)
        self.radioButton_capture = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_capture.setObjectName("radioButton_capture")
        self.horizontalLayout.addWidget(self.radioButton_capture)
        self.pushButton_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(910, 90, 169, 110))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.spinBox_Interval = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_Interval.setMinimum(0)
        self.spinBox_Interval.setMaximum(99999)
        self.spinBox_Interval.setSingleStep(10)
        self.spinBox_Interval.setProperty("value", 1000)
        self.spinBox_Interval.setObjectName("spinBox_Interval")
        self.gridLayout_2.addWidget(self.spinBox_Interval, 5, 1, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_2.addWidget(self.spinBox_3, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.spinBox_expo = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_expo.setMinimum(3)
        self.spinBox_expo.setMaximum(30000)
        self.spinBox_expo.setSingleStep(10)
        self.spinBox_expo.setProperty("value", 40)
        self.spinBox_expo.setObjectName("spinBox_expo")
        self.gridLayout_2.addWidget(self.spinBox_expo, 4, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(910, 220, 269, 183))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_neuron1 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_neuron1.setObjectName("checkBox_neuron1")
        self.gridLayout_3.addWidget(self.checkBox_neuron1, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_2_blue = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_2_blue.setObjectName("checkBox_2_blue")
        self.gridLayout_6.addWidget(self.checkBox_2_blue, 2, 0, 1, 1)
        self.spinBox_2_blue = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_2_blue.setObjectName("spinBox_2_blue")
        self.gridLayout_6.addWidget(self.spinBox_2_blue, 2, 1, 1, 1)
        self.checkBox_2_red = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_2_red.setObjectName("checkBox_2_red")
        self.gridLayout_6.addWidget(self.checkBox_2_red, 1, 0, 1, 1)
        self.spinBox_2_red = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_2_red.setObjectName("spinBox_2_red")
        self.gridLayout_6.addWidget(self.spinBox_2_red, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 2, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.spinBox_1_red = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_1_red.setObjectName("spinBox_1_red")
        self.gridLayout_5.addWidget(self.spinBox_1_red, 0, 2, 1, 1)
        self.checkBox_1_red = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_1_red.setObjectName("checkBox_1_red")
        self.gridLayout_5.addWidget(self.checkBox_1_red, 0, 1, 1, 1)
        self.spinBox_1_blue = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_1_blue.setObjectName("spinBox_1_blue")
        self.gridLayout_5.addWidget(self.spinBox_1_blue, 1, 2, 1, 1)
        self.checkBox_1_blue = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_1_blue.setObjectName("checkBox_1_blue")
        self.gridLayout_5.addWidget(self.checkBox_1_blue, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 1, 1, 1, 1)
        self.checkBox_neoron2 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_neoron2.setObjectName("checkBox_neoron2")
        self.gridLayout_3.addWidget(self.checkBox_neoron2, 2, 0, 1, 1)
        self.checkBox_sti = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_sti.setObjectName("checkBox_sti")
        self.gridLayout_3.addWidget(self.checkBox_sti, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(910, 430, 169, 141))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_sti_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_sti_2.setObjectName("checkBox_sti_2")
        self.gridLayout_4.addWidget(self.checkBox_sti_2, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_4.addWidget(self.spinBox, 1, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_4.addWidget(self.spinBox_4, 3, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_4.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_4.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_4.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.gridLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.gridLayoutWidget_3.raise_()
        self.gridLayoutWidget_2.raise_()
        self.gridLayoutWidget_3.raise_()
        self.gridLayoutWidget_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_neuron1.setText(_translate("MainWindow", "Neuron1"))
        self.label_neuron2.setText(_translate("MainWindow", "Neuron2"))
        self.radioButton_pre.setText(_translate("MainWindow", "Preview"))
        self.radioButton_capture.setText(_translate("MainWindow", "Capture"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.label_3.setText(_translate("MainWindow", "Number"))
        self.label_2.setText(_translate("MainWindow", "Interval[ms]"))
        self.label.setText(_translate("MainWindow", "Exposure[ms]"))
        self.checkBox_neuron1.setText(_translate("MainWindow", "Neuron 1"))
        self.checkBox_2_blue.setText(_translate("MainWindow", "Blue"))
        self.checkBox_2_red.setText(_translate("MainWindow", "Red"))
        self.checkBox_1_red.setText(_translate("MainWindow", "Red"))
        self.checkBox_1_blue.setText(_translate("MainWindow", "Blue"))
        self.checkBox_neoron2.setText(_translate("MainWindow", "Neuron 2"))
        self.checkBox_sti.setText(_translate("MainWindow", "Power Projector"))
        self.checkBox_sti_2.setText(_translate("MainWindow", "Power LED"))
        self.checkBox.setText(_translate("MainWindow", "395nm"))
        self.checkBox_2.setText(_translate("MainWindow", "470nm"))
        self.checkBox_3.setText(_translate("MainWindow", "540nm"))

from pyqtgraph import GraphicsView
